---
abstract: unknown
author:
  - 'Ivan Baktsheev <dot.and.thing@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.59, CPAN::Meta::Converter version 2.112150'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBI-Easy
no_index:
  directory:
    - t
    - inc
requires:
  Class::Easy: 0.17
  DBD::SQLite: 1.25
  DBI: 1.611
  Time::Piece: 1.20
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=DBI-Easy
  homepage: http://perlhug.com
  license: http://dev.perl.org/licenses/
  repository: git://web-app.git.sourceforge.net/gitroot/perl-easy/perl-easy
version: 0.24
